name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the code
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) Set an environment variable with current date
      - name: Set DATE environment variable
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      # 3) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4) Build & push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:${{ env.DATE }}
